CREATE TABLE buses
(
    bus_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_num     VARCHAR(16)                              NOT NULL,
    bus_pla     VARCHAR(6)                               NOT NULL,
    bus_fec_cre TIMESTAMP with time zone                 NOT NULL,
    bus_car     VARCHAR(512)                             NOT NULL,
    bus_mar     VARCHAR(20)                              NOT NULL,
    bus_est     VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_buses PRIMARY KEY (bus_id)
);

CREATE TABLE usuarios
(
    usu_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usu_nom     VARCHAR(100)                             NOT NULL,
    usu_con     VARCHAR(255)                             NOT NULL,
    usu_nom_com VARCHAR(100)                             NOT NULL,
    usu_ape_pat VARCHAR(50)                              NOT NULL,
    usu_ape_mat VARCHAR(50)                              NOT NULL,
    usu_per     VARCHAR(20)                              NOT NULL,
    usu_est     VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (usu_id)
);

ALTER TABLE buses
    ADD CONSTRAINT uc_buses_bus_num UNIQUE (bus_num);

ALTER TABLE buses
    ADD CONSTRAINT uc_buses_bus_pla UNIQUE (bus_pla);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_usu_nom UNIQUE (usu_nom);