CREATE TABLE marcas
(
    mar_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mar_nom VARCHAR(25)                             NOT NULL,
    CONSTRAINT pk_marcas PRIMARY KEY (mar_id)
);

CREATE TABLE buses
(
    bus_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_num     VARCHAR(16)                             NOT NULL,
    bus_pla     VARCHAR(6)                              NOT NULL,
    bus_fec_cre TIMESTAMP with time zone                NOT NULL,
    bus_car     VARCHAR(512)                            NOT NULL,
    bus_mar_id  BIGINT                                  NOT NULL,
    bus_est     VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_buses PRIMARY KEY (bus_id)
);

CREATE TABLE usuarios
(
    usu_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usu_nom     VARCHAR(100)                            NOT NULL,
    usu_con     VARCHAR(255)                            NOT NULL,
    usu_nom_com VARCHAR(200)                            NOT NULL,
    usu_per     VARCHAR(20)                             NOT NULL,
    usu_est     VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (usu_id)
);

ALTER TABLE marcas
    ADD CONSTRAINT uc_marcas_mar_nom UNIQUE (mar_nom);

ALTER TABLE buses
    ADD CONSTRAINT uc_buses_bus_num UNIQUE (bus_num);

ALTER TABLE buses
    ADD CONSTRAINT uc_buses_bus_pla UNIQUE (bus_pla);

ALTER TABLE buses
    ADD CONSTRAINT FK_BUSES_ON_BUS_MAR FOREIGN KEY (bus_mar_id) REFERENCES marcas (mar_id);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_usu_nom UNIQUE (usu_nom);