INSERT INTO marcas (mar_id, mar_nom)
VALUES (1, 'Volvo'),
       (2, 'Scania'),
       (3, 'Fiat'),
       (4, 'Mercedes Benz'),
       (5, 'Renault');

INSERT INTO buses (bus_num, bus_pla, bus_fec_cre, bus_car, bus_mar_id, bus_est)
VALUES ('CIVA-24060001', 'B1X456', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24060002', 'F3Z821', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24060003', 'L7R390', now(), 'Tecnología avanzada, motores eficientes, interiores espaciosos, y sistemas de seguridad ideales para recorridos turísticos.', 2, 'ACTIVO'),
       ('CIVA-24060004', 'T8Y014', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24070001', 'J6K782', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24070002', 'V2C346', now(), 'Tecnología avanzada, motores eficientes, interiores espaciosos, y sistemas de seguridad ideales para recorridos turísticos.', 2, 'ACTIVO'),
       ('CIVA-24070003', 'X5N934', now(), 'Tecnología avanzada, motores eficientes, interiores espaciosos, y sistemas de seguridad ideales para recorridos turísticos.', 2, 'ACTIVO'),
       ('CIVA-24070004', 'R4H213', now(), 'Económicos, versátiles, buena maniobrabilidad y comodidad suficiente para excursiones turísticas accesibles.', 5, 'ACTIVO'),
       ('CIVA-24080001', 'P9L870', now(), 'Elegancia, acabados de lujo, sistemas de entretenimiento y comodidad superior para el turismo premium.', 4, 'ACTIVO'),
       ('CIVA-24080002', 'D3T651', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24080003', 'G8M432', now(), 'Tecnología avanzada, motores eficientes, interiores espaciosos, y sistemas de seguridad ideales para recorridos turísticos.', 2, 'ACTIVO'),
       ('CIVA-24080004', 'N7W895', now(), 'Tecnología avanzada, motores eficientes, interiores espaciosos, y sistemas de seguridad ideales para recorridos turísticos.', 2, 'ACTIVO'),
       ('CIVA-24080005', 'Q2Z187', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24090001', 'H4F019', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24090002', 'Z6Y720', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24090003', 'K9X804', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24090004', 'B3R653', now(), 'Económicos, versátiles, buena maniobrabilidad y comodidad suficiente para excursiones turísticas accesibles.', 5, 'ACTIVO'),
       ('CIVA-24090005', 'Y5T291', now(), 'Económicos, versátiles, buena maniobrabilidad y comodidad suficiente para excursiones turísticas accesibles.', 5, 'ACTIVO'),
       ('CIVA-24100001', 'V7P140', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24100002', 'X2L360', now(), 'Elegancia, acabados de lujo, sistemas de entretenimiento y comodidad superior para el turismo premium.', 4, 'ACTIVO'),
       ('CIVA-24100003', 'J9H457', now(), 'Elegancia, acabados de lujo, sistemas de entretenimiento y comodidad superior para el turismo premium.', 4, 'ACTIVO'),
       ('CIVA-24110001', 'M6N831', now(), 'Elegancia, acabados de lujo, sistemas de entretenimiento y comodidad superior para el turismo premium.', 4, 'ACTIVO'),
       ('CIVA-24110002', 'T4C912', now(), 'Eficiencia en consumo de combustible, diseño compacto, asientos cómodos y confiables para viajes cortos y medianos.', 3, 'ACTIVO'),
       ('CIVA-24110003', 'R7K520', now(), 'Asientos reclinables, sistema de climatización, gran capacidad de equipaje, diseño seguro y cómodo para largas distancias.', 1, 'ACTIVO'),
       ('CIVA-24110004', 'F8W376', now(), 'Elegancia, acabados de lujo, sistemas de entretenimiento y comodidad superior para el turismo premium.', 4, 'ACTIVO');
